# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-14 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='utoken',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
